import org.slf4j.event.Level

plugins {
    `java-library`
    `maven-publish`
    id("net.neoforged.moddev").version("2.0.141")
    idea
    id("io.freefair.lombok") version "9.2.0"
    kotlin("jvm")
}

val modVersion = findProperty("mod_version") as String
val modGroupId = findProperty("mod_group_id") as String
val modId = findProperty("mod_id") as String
val neoVersion = findProperty("neo_version") as String
val minecraftVersion = findProperty("minecraft_version") as String
val minecraftVersionRange = findProperty("minecraft_version_range") as String
val modName = findProperty("mod_name") as String
val modLicense = findProperty("mod_license") as String

tasks.named<Wrapper>("wrapper").configure {
    distributionType = Wrapper.DistributionType.ALL
}

version = modVersion
group = modGroupId

sourceSets {
    main {
        resources {
            // Include resources generated by data generators.
            srcDir("src/generated/resources")

            // Exclude common development only resources from finalized outputs
            exclude("**/*.bbmodel") // BlockBench project files
            exclude("src/generated/**/.cache") // datagen cache files
        }
    }

    create("datagen") {
        java.srcDir("src/datagen/java")

        compileClasspath += main.get().output
        runtimeClasspath += main.get().output
    }

    create("earlycheck") {
        java.srcDir("src/earlycheck/java")

        compileClasspath += main.get().output
        runtimeClasspath += main.get().output
    }
}

repositories {
    // Add here additional repositories if required by some of the dependencies below.
    mavenCentral()
    maven {
        name = "Modrinth"
        url = uri("https://api.modrinth.com/maven")
    }

    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = uri("https://maven.blamejared.com/")
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = uri("https://modmaven.dev")
    }
}

base {
    archivesName = modId
}

// Mojang ships Java 25 to end users in 26.1, so mods should target Java 25.
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

tasks {
    // runs the same runtime check without initializing game.
    // this task is not strictly required before running client, because the same check will run during mod initialization.
    // however, running it early will detect issues with the mod custom registry more efficiently.

    // actually, I don't know how to write annotation processor to check registries at compile time.
    // So this is actually an alternative.
    val runEarlyCheck = register<JavaExec>("runEarlyCheck") {
        description = "To make sure all of custom auto registers are correct."
        classpath = sourceSets["earlycheck"].runtimeClasspath
        mainClass = "com.mistbeyond.examplemod.earlycheck.Main"
        args = listOf("source", sourceSets.main.get().output.asPath)
    }

    build.get().dependsOn(runEarlyCheck)
}

neoForge {
    // Specify the version of NeoForge to use.
    version = neoVersion

    // This line is optional. Access Transformers are automatically detected
    // accessTransformers = project.files("src/main/resources/META-INF/accesstransformer.cfg")

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        create("client") {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        create("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("data") {
            clientData()
            sourceSet.set(sourceSets.getByName("datagen"))
            programArguments.addAll(
                "--mod",
                modId,
                "--all",
                "--existing",
                file("src/main/resources/").absolutePath,
                "--output",
                file("src/generated/resources").absolutePath
            )
        }


        // applies to all the run configs above
        configureEach {
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty("forge.logging.markers", "REGISTRIES")
            jvmArgument("-XX:+AllowEnhancedClassRedefinition")

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = Level.DEBUG
            // tasksBefore = listOf(tasks.named("runEarlyCheck"))
        }
    }

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // multi mod projects should define one per mod
        create(modId) {
            sourceSet(sourceSets.main.get())
            sourceSet(sourceSets["datagen"])
        }
    }
}

// Sets up a dependency configuration called "localRuntime".
// This configuration should be used instead of "runtimeOnly" to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    val localRuntime = maybeCreate("localRuntime")
    named("runtimeClasspath") { extendsFrom(localRuntime) }
    named("datagenRuntimeClasspath") { extendsFrom(runtimeClasspath.get()) }
    named("datagenCompileClasspath") { extendsFrom(compileClasspath.get()) }
    named("earlycheckRuntimeClasspath") { extendsFrom(runtimeClasspath.get()) }
    named("earlycheckCompileClasspath") { extendsFrom(compileClasspath.get()) }
}

dependencies {
    fun DependencyHandler.localRuntime(dep: Any) = add("localRuntime", dep)
    val jeiVersion = findProperty("jei_version") as String
    val jadeVersion = findProperty("jade_version") as String

    // datagen
    "datagenImplementation"(kotlin("stdlib"))

    // JEI
    compileOnly("mezz.jei:jei-${minecraftVersion}-common-api:${jeiVersion}")
    compileOnly("mezz.jei:jei-${minecraftVersion}-neoforge-api:${jeiVersion}")
    localRuntime("mezz.jei:jei-${minecraftVersion}-neoforge:${jeiVersion}")

    // Jade
    compileOnly("maven.modrinth:jade:${jadeVersion}")
    localRuntime("maven.modrinth:jade:${jadeVersion}")
}

var generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
    description = ""
    var replaceProperties = mapOf(
        "minecraft_version" to minecraftVersion,
        "minecraft_version_range" to minecraftVersionRange,
        "neo_version" to neoVersion,
        "mod_id" to modId,
        "mod_name" to modName,
        "mod_license" to modLicense,
        "mod_version" to modVersion,
    )
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from("src/main/templates")
    into("build/generated/sources/modMetadata")
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main {
    resources.srcDir { generateModMetadata }
}
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask(generateModMetadata)

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri(layout.projectDirectory.dir("repo"))
        }
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8" // Use the UTF-8 charset for Java compilation
}


// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}

kotlin {
    jvmToolchain(25)
}